### ISSUE TITLE
Error when running ejbca-setup.sh

### ISSUE THREAD

**Issue by p4pifor** [primekeydevs/ejbca-ce#10]
I am installing ejbca on a linux machine,(ubuntu 20.04), I follow the steps at ejbca quick star guide: https://doc.primekey.com/ejbca6152/tutorials-and-guides/quick-start-guide . However, whenever I run the script
`./<ejbca-install-directory>/bin/extra/ejbca-setup` 

I got the following errors: 

`Init database`
`Dropping all database tables in database ejbcatest (using the script ejbca/doc/sql-scripts/drop-tables-ejbca-mysql.sql), using DB user ejbca, who should have privileges to do that`
`ERROR 1146 (42S02) at line 1: Table 'ejbcatest.AccessRulesData' doesn't exist`
`ERROR 1146 (42S02) at line 2: Table 'ejbcatest.AdminEntityData' doesn't exist`

The script continues executing,but at the step of running wildfly, it ends in failure and the script is stopped. Could anybody tell me what this error was due to? 
Thanks in advance :)

**Comment by primetomas** [comment]
The error about database table should be nothing to worry about. It just means that there is no existing database present to drop, if you were installing over an old installation those tables would be dropped and recreated.

The failure of WildFly would be more interesting, and probably tells more about the actual cause.

**Comment by p4pifor** [comment]
Hi, thank you so much for the answer Thomas. Are there any requirements my system must satisfy or any software/packets required before following the installation at quick star guide? As far as I understood, "ejbca-setup.sh" script installs all dependencies, but I may be wrong. Thanks in advance

**Comment by p4pifor** [comment]
Hi, thanks for your answer Tomas, I managed to install it. Afterwards, the installation is completed and the password to install superadmin is provided. However, when I write that password when executing superadmin.p12 it says: wrong password. Is there any problem if I do not install superadmin in my browser? Thanks in advance

**Comment by primetomas** [comment]
If you don't install the superadmin.p12 in the web browser you will not be able to access the Admin Web UI. EJBCA will still work fine :-), you can use the CLI etc. But it's really useful to be able to access the web UI. It is possible, completely from the CLI to generate a new superadmin.p12 (with a new set pwd).

**Comment by p4pifor** [comment]
Hi thank you so much, I've changed the password and superadmin.p12 is installed, it worked :-). However, I try to access to `https://localhost:8443/ejbca/adminweb/` but I cannot connect to it. Everything is running, I can access to ejbca using the terminal but not to the web UI, do you have any idea of what I may be missing to configure? Or what could be wrong? Thanks in advance

**Comment by primetomas** [comment]
That is typically TLS configuration. The most usual that superadmin is not installed in the browser :-)

Try https://localhost:8443/ejbca to check TLS and web UI is working. Then check server.log for errors during deploy/startup.

**Comment by p4pifor** [comment]
It seems port 8443 is closed, I've scanned ports with nmap. Is there any extra configuration required that's not explained in quick start guide? I've run the script and everything end in success, the superadmin is installed in my browser but I cannot connect neither to https://localhost:8443/ejbca/adminweb/ nor to  https://localhost:8443/ejbca . Thank you very much for your help

**Comment by primetomas** [comment]
Sorry, it was supposed to say port 8442 above. 8442 does not require client certificate authentication.

**Comment by p4pifor** [comment]
Hi, I cannot access neither to 8443 nor to 8442. If I try https://localhost:8080/ejbca, I can see the public EJBCA pages, but if I wanna do some kind of task (i.g. create certificate) I am asked to provide a username and an enrollment code. I am working with the latest version of ejbca ce(7_4_3_2). Do I need any specific requirement in my system? I am working with light ubuntu 16.04. Thanks Tomas

**Comment by primetomas** [comment]
Did you install using the setup script, or manually with the installation instructions? Sounds like TLS was not configured in Wildfly correctly.
check the installation instructions, that has a part for TLS configuration. Also check wildfly server log during a fresh start for errors, if TLS is not configured at all there should be log entries when it tries to start the connectors for ports 8443 and 8442.

**Comment by primetomas** [comment]
the username/enrollment code is as it should.

**Comment by p4pifor** [comment]
I've installed it using the setup script. 

> Looking at wildfly logs I found the following errors:

`ERROR [org.jboss.as.jsf] (MSC service thread 1-1) WFLYJSF0002: Could not load JSF managed bean class: org.ejbca.ui.web.admin.peerconnector.PeerConnectorsMBean`
`ERROR [org.jboss.as.jsf] (MSC service thread 1-1) WFLYJSF0002: Could not load JSF managed bean class: org.ejbca.ui.web.admin.peerconnector.PeerConnectorMBean`

> This info:

`WFLYUT0006: Undertow HTTPS listener httpspriv listening on 0.0.0.0:8443 `
`WFLYUT0007: Undertow HTTPS listener https stopped, was bound to 0.0.0.0:8443`

> This warning:
WARN  [org.jboss.as.server.deployment] (MSC service thread 1-3) WFLYSRV0003: Could not index class META-INF/versions/9/module-info.class at /content/ejbca.ear/lib/bctls-jdk15on-168

Thank you so much for your help

**Comment by primetomas** [comment]
What Java version are you using? Java made some changes recently that may have broken something.  At least by rumor, didn't see/try it myself.

**Comment by p4pifor** [comment]
Hi, I am using: openjdk version: "1.8.0_292"
As we've got the option of doing it with CLI commands, I'll do it that way, the problem 
 must be related with java version, thank you Tomas

**Comment by p4pifor** [comment]
Btw, how do you run ejbca service once you have install it? I mean, whenever I shutdown my machine, the ejbca instance disappears and I have to execute ejbca-setup.sh again the next time I log in in order to get it, but this script downloads everything again. Then, I guess there should be another option to start the service once you everything is installed, however, I cannot find info about it.

**Comment by primetomas** [comment]
The script runs standalone.sh in the wildfly directory. After a shutdown you can simply start the already installed wildfly with standalone.sh again. You'll should only run ejbca-setup once (unless you intend too reinstall). 

It's possible to install wildfly as a Linux service, theres instructions for that at wildfly (and services scripts are included in there wildfly directory)

**Comment by primetomas** [comment]
I tried the ejbca-setup.sh scripts myself now, with the latest EJBCA code checked out from git. I had to add an extra delay after checking if wildfly was running to prevent the script from terminating due to JBoss not up. May be due to my system being too slow or something (should not be though). After that it worked fine.

diff --git a/bin/extra/ejbca-setup.sh b/bin/extra/ejbca-setup.sh
index 0d26e6c8a3..9b593caf77 100755
--- a/bin/extra/ejbca-setup.sh
+++ b/bin/extra/ejbca-setup.sh
@@ -163,6 +163,8 @@ wildfly_check() {
   for i in `seq 1 $DURATION`; do
     wildfly/bin/jboss-cli.sh --connect ":read-attribute(name=server-state)" | grep "result" | awk '{ print $3; }'|grep running
     if [ $? -eq 0 ]; then
+           echo "sleeping 10s"
+           sleep 10
       return 0
     fi
     sleep 5

**Comment by primetomas** [comment]
The script starts WildFly with:
nohup wildfly/bin/standalone.sh -b 0.0.0.0 > /dev/null 2> /dev/null &

If it's running already you can see with "ps -ef|grep java". Kill old wildfly running and starting again should be no problem.

**Comment by p4pifor** [comment]
Thank you so much Tomas! Everything works fine :-)
