### ISSUE TITLE
Run ejbca in a different host, not in localhost

### ISSUE THREAD

**Issue by p4pifor** [primekeydevs/ejbca-ce#11]
I am trying to run ejbca on a virtual network. In such a way that I have a client(10.0.2.2) in a host and the ejbca(10.0.4.4) in another. I wanna let the client interact with ejbca server from its machine, thus, I've tried the following:

- First, create a user granting him privileges to access to mariadb from its ip address: https://linuxhint.com/expose_mysql_server_internet/

-Then, modify ejbca-setup.sh switching the following parameters from localhost to 10.0.4.4:
`httpsserver_hostname=¨10.0.4.4¨
database_host= ¨10.0.4.4¨`

The proccess of deploying EJBCA in the new host ends in failure, only wildfly is deployed with success.

**Logs:**
`ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 65) MSC000001: Failed to start service jboss.persistenceunit."ejbca.ear#ejbca": org.jboss.msc.service.StartException in service jboss.persistenceunit."ejbca.ear#ejbca": javax.persistence.PersistenceException: [PersistenceUnit: ejbca] Unable to build Hibernate SessionFactory`

`ERROR [org.jboss.as.controller.management-operation] (DeploymentScanner-threads - 2) WFLYCTL0013: Operation ("deploy") failed - address:`

`"WFLYCTL0080: Failed services" => {"jboss.persistenceunit.\"ejbca.ear#ejbca\"" => "org.jboss.msc.service.StartException in service jboss.persistenceunit.\"ejbca.ear#ejbca\": javax.persistence.PersistenceException: [PersistenceUnit: ejbca] Unable to build Hibernate SessionFactory`

`ERROR [org.jboss.as.controller.management-operation] (DeploymentScanner-threads - 2) WFLYCTL0013: Operation ("deploy") failed - address: ([("deployment" => "ejbca.ear")]) - failure description: {`

	`Caused by: javax.persistence.PersistenceException: [PersistenceUnit: ejbca] Unable to build Hibernate SessionFactory
	Caused by: org.hibernate.tool.schema.spi.SchemaManagementException: Unable to open JDBC connection for schema management target
	Caused by: java.sql.SQLException: javax.resource.ResourceException: IJ000453: Unable to get managed connection for java:/EjbcaDS
	Caused by: javax.resource.ResourceException: IJ000453: Unable to get managed connection for java:/EjbcaDS
	Caused by: javax.resource.ResourceException: IJ031084: Unable to create connection
	Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=10.0.4.4)(port=3306)(type=master) : Connection refused (Connection refused)
	Caused by: java.net.ConnectException: Connection refused (Connection refused)"},
	"WFLYCTL0412: Required services that are not installed:" => ["jboss.persistenceunit.\"ejbca.ear#ejbca\""],
	"WFLYCTL0180: Services with missing/unavailable dependencies" => undefined
}`

Is there any other parammeter I should change or something I'm not doing well? I really appreciate any kind of help, thanks in advance

**Comment by primetomas** [comment]
The error is from the network layer.

Could not connect to address=(host=10.0.4.4)(port=3306)(type=master) : Connection refused

Either your firewall does not let port 3306 through, or your database is not listening externally.

**Comment by primekeydevs** [comment]
Closed due to inactivity
