### ISSUE TITLE
Add End Entity Miss CA List after enable System Configuration Enable Session Timeout

### ISSUE THREAD

**Issue by JoeyChen-NTUT** [primekeydevs/ejbca-ce#12]
env:primekey/ejbca-ce:latest  

Before System Configuration > Enable Session Timeout  Enabled  
Add End Entity > Main Certificate Data > CA list is missing(empty)  

Before:  
![image](https://user-images.githubusercontent.com/40187978/140011203-4dc70ddc-9d4a-4445-aaa7-67006675db10.png)
![image](https://user-images.githubusercontent.com/40187978/140011216-03b29bb8-610e-4409-b423-cab08aa6c59b.png)

After:  
![image](https://user-images.githubusercontent.com/40187978/140011233-b7a4d7e5-b9c6-42ec-adb3-05f1358147dd.png)
![image](https://user-images.githubusercontent.com/40187978/140011241-bf8e7eb1-1524-4fca-bf0a-f8e1060232ac.png)

**Comment by primetomas** [comment]
Interesting, I could reproduce this.

**Comment by primetomas** [comment]
We found this existing issue: https://jira.primekey.se/browse/ECA-8927

**Comment by primetomas** [comment]
You can track the issue in Jira. Thanks for the report!
