### ISSUE TITLE
EJBCA Certificate Enrollment Error (Not Allow Signature Algorithm Different from CA)

### ISSUE THREAD

**Issue by JoeyChen-NTUT** [primekeydevs/ejbca-ce#14]
I have a question about when I use different Signature Algorithm Certificate profile against form CA
Such like CA is using SHA512ECDSA and Certificate profile is setting up to SHA256RSA
will get the enrollment error below

```
EJBCA Certificate Enrollment Error
Username: 
Request failed. org.bouncycastle.operator.OperatorCreationException: cannot create signer: Supplied key
(org.bouncycastle.jcajce.provider.asymmetric.ec.BCECPrivateKey) is not a RSAPrivateKey instance
```

**Comment by primetomas** [comment]
Hi, This is as it should be. If the CA has an EC key, it can not sign with an RSA signature algorithm. A CA that has an EC key, i.e. Root CA that has signed itself with ECDSA, can only issue certificates signed using an ECDSA signature algorithm. This is the nature of the cryptography.

Set the Certificate Profile setting to SHA256WithECDSA (or SHA384WithECDSA or SHA512WithECDSA)...

Cheers,
Tomas
