### ISSUE TITLE
Issue with Subject Alternative Names and re-key

### ISSUE THREAD

**Issue by jmrenshaw** [primekeydevs/ejbca-ce#20]
I have been testing CMP for OpenSSL using the [generic CMP client ](https://github.com/siemens/gencmpclient) and run into some trouble with Key Update Request (KUR) messages where the end entity has a DNS name set as the SAN which matches their CN.  In end-entity profile I have:
Subject Alternative Name: DNS Name
- [x] Use entity CN field 
- [ ] Required
- [x] Modifiable
- [ ] Validation

My Initialisation Request seems to work fine but the KUR constantly fails with

> ERROR: received PKIStatus: rejection; PKIFailureInfo: badRequest; StatusString: "Wrong number of DNSNAME fields in Subject Alternative Name."

I have tried multiple variations of the config above and I can't seem to get it to work.  IR and KUR when I remove the SAN config work fine.

I have also tried to rekey manually by uploading a CSR to the web portal.  But when I tried to change the status of the end-entity to new I got a similar message, see attached.
![EJBCA](https://user-images.githubusercontent.com/23117233/149959197-3dd78407-8e2d-4bd2-bf5e-196341b7baab.PNG)

Not sure whether this is a problem with my configuration or a bug so any help would be appreciated.

**Comment by primetomas** [comment]
Try unchecking "Use entity CN field" that is designed for automatic population of the DNSName alname field in the RA UI and should not do anything relevant when using protocols. 
If your CMP request contains multiple DNSName you need to add multiple DNSNames in the end entity profile as well.

**Comment by jmrenshaw** [comment]
Thank you Tomas, I have resolved my issue now. It was a combination of the use CN option as you suggested and an error on my part in the syntax of the SAN on the client side.

**Comment by primetomas** [comment]
Great!
