### ISSUE TITLE
SSL_CLIENT_CERT header ignored in ejbca-ce docker image

### ISSUE THREAD

**Issue by gardellajuanpablo** [primekeydevs/ejbca-ce#21]
I am testing docker `primekey/ejbca-ce:7.4.3.2` using following environment variables in a docker compose file:

``` 
  ejbca-ce:
    image: primekey/ejbca-ce:${EJBCA_VERSION}
    environment:
      - DATABASE_JDBC_URL=${EJBCA_DB_JDBCURL}
      - DATABASE_USER=${EJBCA_DB_USER}
      - DATABASE_PASS=${EJBCA_DB_PASS}
      - PROXY_HTTP_BIND=0.0.0.0
```
haproxy 2.5.1 configuration:

``` 
frontend http-in
   bind :8000
   bind :8443 ssl crt-list /etc/mycerts/cert-list.txt ca-file /etc/mycerts/CA.pem verify optional 
   http-request set-header SSL_CLIENT_CERT %{+Q}[ssl_c_der,base64] if { ssl_c_used }
   acl prefixed-with-ejbca path_beg /ejbca
   option forwardfor
   use_backend ejbca if prefixed-with-ejbca

 backend ejbca
    mode http
    http-request set-header X-Forwarded-Proto https
    http-request set-header X-Forwarded-Port %[dst_port]
    server server1 "${EJBCA_HOST}":8082 
``` 

Using https://foohost/ejbca/adminweb ask the certificate properly but it failed that certificate is not presented. Same approach I used for [Keycloak behind haproxy](https://www.keycloak.org/docs/latest/server_admin/#client-certificate-lookup). In official documentation I did not find any reference that this header is handled in ejbca. Is that a feature that was not developed yet? Before that, I was using [Setting up a HA Proxy in front of EJBCA](https://doc.primekey.com/ejbca/ejbca-integration/integrating-with-third-party-applications/setting-up-a-ha-proxy-in-front-of-ejbca); but I would like to hide the port and use this approach. 

Am I missing something or this is documented but still not available in community edition? Is required to create keystore/trustore files? 

Logs:
```
ejbca.lakaut.com        | 2022-01-19 00:04:00,527+0000 INFO  [/opt/primekey/bin/start.sh] (process:1) Enabling HTTP proxy listeners on 0.0.0.0:8081 and 0.0.0.0:8082.
ejbca.lakaut.com        | 2022-01-19 00:04:08,676+0000 INFO  [/opt/primekey/bin/start.sh] (process:1) Health check now reports application status at /ejbca/publicweb/healthcheck/ejbcahealth
ejbca.lakaut.com        | 2022-01-19 00:04:09,590+0000 ERROR [org.ejbca.ui.web.admin.configuration.EjbcaJSFHelperImpl] (default task-1) org.cesecore.authentication.AuthenticationFailedException: Client certificate or OAuth bearer token required.
ejbca.lakaut.com        | 2022-01-19 00:04:09,604+0000 WARN  [org.ejbca.ui.web.admin.configuration.EjbcaWebBeanImpl] (default task-1) Language was not initialized for this session

```

**Comment by primetomas** [comment]
Does this answer your question?
https://sourceforge.net/p/ejbca/discussion/123123/thread/b37f58cf33/
In general SSL_CLIENT_CERT is controlled by https://docs.wildfly.org/25/wildscribe/subsystem/undertow/server/http-listener/index.html#attr-certificate-forwarding

**Comment by gardellajuanpablo** [comment]
Thanks @primetomas I believe docker `resources/functions-appserver` file inside docker is fine.  It generates following configuration:

```
<subsystem xmlns="urn:jboss:domain:undertow:11.0" default-server="default-server" default-virtual-host="default-host" default-servlet-container="default" statistics-enabled="${wildfly.undertow.statistics-enabled:${wildfly.statistics-enabled:false}}">
            <buffer-cache name="default"/>
            <server name="default-server">
                <http-listener name="remoting" socket-binding="remoting" enable-http2="true"/>
                <http-listener name="proxy-https-listener" socket-binding="proxy-https" max-post-size="33554432" allow-encoded-slash="true" secure="true" certificate-forwarding="true" proxy-address-forwarding="true"/>
                <http-listener name="proxy-http-listener" socket-binding="proxy-http" max-post-size="33554432" allow-encoded-slash="true" redirect-socket="proxy-https" proxy-address-forwarding="true"/>
                <host name="default-host" alias="localhost">
                    <filter-ref name="redirect-to-app" predicate="method(GET) and not path-prefix('/ejbca/','/.well-known/','/signserver/') and not equals({%{LOCAL_PORT}, 4447})" priority="1"/>
                    <http-invoker/>
                </host>
            </server>
            <servlet-container name="default">
                <jsp-config/>
                <websockets/>
            </servlet-container>
            <filters>
                <rewrite name="redirect-to-app" target="/${env.APPLICATION_NAME:.well-known}/" redirect="true"/>
            </filters>
        </subsystem>
        [...]
    <socket-binding-group name="standard-sockets" default-interface="management" port-offset="${jboss.socket.binding.port-offset:0}">
        <socket-binding name="management-http" interface="management" port="${jboss.management.http.port:9990}"/>
        <socket-binding name="proxy-http" interface="proxy-http" port="8081"/>
        <socket-binding name="proxy-https" interface="proxy-http" port="8082"/>
        <socket-binding name="remoting" interface="management" port="4447"/>
        <socket-binding name="txn-recovery-environment" port="4712"/>
        <socket-binding name="txn-status-manager" port="4713"/>
        <outbound-socket-binding name="ejbca-mail-smtp">
            <remote-destination host="${env.SMTP_DESTINATION:localhost}" port="${env.SMTP_DESTINATION_PORT:25}"/>
        </outbound-socket-binding>
    </socket-binding-group>
``` 

Behind the scene, undertow [SSL handler](https://undertow.io/undertow-docs/undertow-docs-2.1.0/index.html#ssl-headers-handler) is used, which is implemented at [SSLHeaderHandler.java#86](https://github.com/undertow-io/undertow/blob/master/core/src/main/java/io/undertow/server/handlers/SSLHeaderHandler.java#L86). I am not sure if using it will populate the handlers that is expected at [EjbcaWS.java#L235](https://github.com/primekeydevs/ejbca-ce/blob/main/modules/ejbca-ws/src/org/ejbca/core/protocol/ws/EjbcaWS.java#L235) for example. For some reason Keycloak is not using that approach and has a [custom provider](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/x509/HaProxySslClientCertificateLookup.java#L52). 

I will do more testing and enable DEBUG level to see if there is an issue at [SSLHeaderHandler.java#L118](https://github.com/undertow-io/undertow/blob/master/core/src/main/java/io/undertow/server/handlers/SSLHeaderHandler.java#L118). Then I will try to access to  [EjbcaWS.java#L235](https://github.com/primekeydevs/ejbca-ce/blob/main/modules/ejbca-ws/src/org/ejbca/core/protocol/ws/EjbcaWS.java#L235) and see if the header is populated properly. 

I will let you if the certificate is populated or not.
