### ISSUE TITLE
Encoding of ExpiredCertsOnCRL GeneralizedTime

### ISSUE THREAD

**Issue by linuxdevel** [primekeydevs/ejbca-ce#8]
Hi

I noticed that encoding of GeneralizedTime in CRL extension ExpiredCertsOnCRL looks wrong, at least according to PKIX.
ejbca-ca adds fractional seconds (set to 000).. And X.690 says that "11.7.3 The fractional-seconds elements, if present, shall omit all trailing '0's; if the elements correspond to 0, they shall be wholly omitted, and the decimal point element also shall be omitted."

In RFC 5280 (PKIX) it is stated that GeneralizedTime should not contain fractional seconds.  The ITU-T X.509 says GeneralizedTime shall be encoded according to ITU-T X.690 / ISO/IEC 8825-1. X.690 does not specify that fractional seconds should be omitted but
according to a fellow crypto/PKI expert (that has written a few RFC's) he says that RFC 5280 should be followed and that this specific issue might have been oversighted when ITU-T X.509/690 was written. 

After some investigations, we have also seen that most commercial CA's out there does not add fractional seconds..

**Comment by primetomas** [comment]
Created this issue. 
https://jira.primekey.se/browse/ECA-10399

**Comment by primetomas** [comment]
Thanks. Will be fixed for the next release.
