### ISSUE TITLE
How to add multiple custom qc statement on certificate profile

### ISSUE THREAD

**Issue by bunyaminatik** [primekeydevs/ejbca-ce#9]
I have checked certificate profiles page on UI and there is only one input field for adding custom qc statement. But I want to add more than one custom qc statement.

Is there any possibility to solve that or should I do customization?

**Comment by primekeydevs** [comment]
Not sure you really want the "custom qc statement". Can you explain what you are looking to add there?

Cheers,
Tomas
________________________________
From: Bünyamin Atik ***@***.***>
Sent: Wednesday, July 14, 2021 1:49:38 PM
To: primekeydevs/ejbca-ce ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [primekeydevs/ejbca-ce] How to add multiple custom qc statement on certificate profile (#9)

CAUTION: External Sender - Be cautious when clicking links or opening attachments. Please email ***@***.*** with any questions.


I have checked certificate profiles page on UI and there is only one input field for adding custom qc statement. But I want to add more than one custom qc statement.

Is there any possibility to solve that or should I do customization?

**Comment by bunyaminatik** [comment]
![custom-qc](https://user-images.githubusercontent.com/8708460/125901696-73b569ac-581c-407c-bfff-a506c3d779ca.jpeg)


As attached image, I added one Custom-QC Statement but i want to add more. There is no option to add another custom qc statement at certificate profiles page.

**Comment by primetomas** [comment]
that's correct. Adding your own strings to QC extensions I actually haven't seen anyone doing before. So this feature is simple and only supports a single entry. If you want to customize extensions completely you can use the Custom Certificate Extension feature instead and create any ASN.1 you like.
https://doc.primekey.com/ejbca/ejbca-operations/ejbca-ca-concept-guide/certificate-profiles-overview/custom-certificate-extensions

**Comment by primetomas** [comment]
There are no plans to enhance this feature as we have not had any requests for it. All users stick to the QC statements standardized in ETSI documents.
